---
- hosts: all
  become: yes
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
       key_name: mykeypair27may23
       instance_type: t2.micro
       image: 
        id: ami-0638cdee28f295709
       wait: yes
       group: launch-wizard-1
       count: 2
       region: us-east-2a
       vpc_subnet_id: subnet-0ce115ac055e6f760
       assign_public_ip: yes
       instance_tags:
         Name: ansiblenodes
