---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks: 
   - name: Installation of apache2 on webserver (ubuntu)
     apt:
      name: "{{mywebpackforubuntu}}"
      state: present

   - name: Restarting of apache2 on webserver (ubuntu)
     service:
      name: "{{mywebpackforubuntu}}"
      state: started

   - name: Installation of httpd on appserver (redhat)
     ansible.builtin.dnf:
      name: "{{mywebpackforredhat}}"
      state: present

   - name: Restarting of httpd on appserver (redhat)
     service:
      name: "{{mywebpackforredhat}}"
      state: present

  