---
- name: Downloading tomcat
  get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
    dest: /home/ubuntu/apache-tomcat-10.0.20.tar.gz
    force_basic_auth: yes

- name: creating a tomcat folder
  file:
    path: /opt/tomcat/
    state: directory


- name: Extract apache-tomcat-10.0.20.tar.gz into /opt/tomcat/
  command:
   cmd: sudo tar xzvf apache-tomcat-10.0.20.tar.gz -C /opt/tomcat --strip-components=1
   creates: /opt/tomcat/LICENCE