---
- name: Downloading tomcat
  get_url:
    url: https://www-eu.apache.org/dist/tomcat/tomcat-10/v10.1.9/bin/apache-tomcat-10.1.9.tar.gz
    dest: /home/ubuntu/apache-tomcat-10.1.9.tar.gz
    force_basic_auth: yes

- name: creating a tomcat folder
  file:
    path: /opt/tomcat/
    State: directory


- name: Extract apache-tomcat-10.1.9.tar.gz into /opt/tomcat/
  command:
   cmd: sudo tar -xf /home/ubuntu/apache-tomcat-10.1.9.tar.gz -C /opt/tomcat/
   creates: /opt/tomcat/LICENCE