---
- name: Grant Tomcat Ownership
  command: "sudo chown -R tomcat: /opt/tomcat"


- name: Grant execute Tomcat permissions on bin folder
  command: sudo sh -c 'chmod +x /opt/tomcat/latest/bin/*.sh'
